# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      ACSEO\UserBundle\Entity\User: plaintext

    role_hierarchy:
      ROLE_USER:  ROLE_USER
      ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
      # main:
      #  entity:
      #   class:    ACSEO\UserBundle\Entity\User
      #   property: username
      in_memory:
        memory:
          users:
            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    #provider:     main
    provider:     in_memory

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
              login_path: login
              check_path: login_check
            logout:
              path:       logout
              target:     login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
